export const STOCKS = [
  { symbol: 'AAPL',  name: 'Apple Inc.',              displaySymbol: 'AAPL.US',  color: '#818cf8', badge: 'STOCK' },
  { symbol: 'MSFT',  name: 'Microsoft Corp.',         displaySymbol: 'MSFT.US',  color: '#60a5fa', badge: 'STOCK' },
  { symbol: 'GOOGL', name: 'Alphabet Inc.',           displaySymbol: 'GOOGL.US', color: '#4ade80', badge: 'STOCK' },
  { symbol: 'AMZN',  name: 'Amazon.com Inc.',         displaySymbol: 'AMZN.US',  color: '#fb923c', badge: 'STOCK' },
  { symbol: 'NVDA',  name: 'Nvidia Corporation',      displaySymbol: 'NVDA.US',  color: '#34d399', badge: 'STOCK' },
  { symbol: 'TSLA',  name: 'Tesla Inc.',              displaySymbol: 'TSLA.US',  color: '#f43f5e', badge: 'STOCK' },
  { symbol: 'META',  name: 'Meta Platforms Inc.',     displaySymbol: 'META.US',  color: '#38bdf8', badge: 'STOCK' },
  { symbol: 'AMD',   name: 'Advanced Micro Devices',  displaySymbol: 'AMD.US',   color: '#e879f9', badge: 'STOCK' },
  { symbol: 'NFLX',  name: 'Netflix Inc.',            displaySymbol: 'NFLX.US',  color: '#f87171', badge: 'STOCK' },
  { symbol: 'INTC',  name: 'Intel Corporation',       displaySymbol: 'INTC.US',  color: '#a78bfa', badge: 'STOCK' },
  { symbol: 'ORCL',  name: 'Oracle Corporation',      displaySymbol: 'ORCL.US',  color: '#f59e0b', badge: 'STOCK' },
  { symbol: 'CRM',   name: 'Salesforce Inc.',         displaySymbol: 'CRM.US',   color: '#22d3ee', badge: 'STOCK' },
  { symbol: 'ADBE',  name: 'Adobe Inc.',              displaySymbol: 'ADBE.US',  color: '#ff4444', badge: 'STOCK' },
  { symbol: 'PYPL',  name: 'PayPal Holdings',         displaySymbol: 'PYPL.US',  color: '#003087', badge: 'STOCK' },
  { symbol: 'COST',  name: 'Costco Wholesale',        displaySymbol: 'COST.US',  color: '#e31837', badge: 'STOCK' },
  { symbol: 'PEP',   name: 'PepsiCo Inc.',            displaySymbol: 'PEP.US',   color: '#004b91', badge: 'STOCK' },
  { symbol: 'KO',    name: 'Coca-Cola Co.',           displaySymbol: 'KO.US',    color: '#f40000', badge: 'STOCK' },
  { symbol: 'WMT',   name: 'Walmart Inc.',            displaySymbol: 'WMT.US',   color: '#ffc220', badge: 'STOCK' },
  { symbol: 'DIS',   name: 'Walt Disney Co.',         displaySymbol: 'DIS.US',   color: '#111111', badge: 'STOCK' },
  { symbol: 'NKE',   name: 'Nike Inc.',               displaySymbol: 'NKE.US',   color: '#000000', badge: 'STOCK' },
  { symbol: 'SBUX',  name: 'Starbucks Corp.',         displaySymbol: 'SBUX.US',  color: '#00704a', badge: 'STOCK' },
  { symbol: 'V',     name: 'Visa Inc.',               displaySymbol: 'V.US',     color: '#1a1f71', badge: 'STOCK' },
  { symbol: 'MA',    name: 'Mastercard Inc.',         displaySymbol: 'MA.US',    color: '#eb001b', badge: 'STOCK' },
  { symbol: 'JPM',   name: 'JPMorgan Chase',          displaySymbol: 'JPM.US',   color: '#117aca', badge: 'STOCK' },
  { symbol: 'BAC',   name: 'Bank of America',         displaySymbol: 'BAC.US',   color: '#0061ff', badge: 'STOCK' },
  { symbol: 'WFC',   name: 'Wells Fargo',             displaySymbol: 'WFC.US',   color: '#d71e28', badge: 'STOCK' },
  { symbol: 'GS',    name: 'Goldman Sachs',           displaySymbol: 'GS.US',    color: '#7399c6', badge: 'STOCK' },
  { symbol: 'MS',    name: 'Morgan Stanley',          displaySymbol: 'MS.US',    color: '#002554', badge: 'STOCK' },
  { symbol: 'IBM',   name: 'IBM Corp.',               displaySymbol: 'IBM.US',   color: '#0530ad', badge: 'STOCK' },
  { symbol: 'CSCO',  name: 'Cisco Systems',           displaySymbol: 'CSCO.US',  color: '#049fd9', badge: 'STOCK' },
  { symbol: 'ORCL',  name: 'Oracle Corp.',            displaySymbol: 'ORCL.US',  color: '#f00000', badge: 'STOCK' },
  { symbol: 'UBER',  name: 'Uber Technologies',       displaySymbol: 'UBER.US',  color: '#000000', badge: 'STOCK' },
  { symbol: 'ABNB',  name: 'Airbnb Inc.',             displaySymbol: 'ABNB.US',  color: '#ff5a5f', badge: 'STOCK' },
  { symbol: 'SHOP',  name: 'Shopify Inc.',            displaySymbol: 'SHOP.US',  color: '#95bf47', badge: 'STOCK' },
  { symbol: 'SPOT',  name: 'Spotify Technology',      displaySymbol: 'SPOT.US',  color: '#1db954', badge: 'STOCK' },
  { symbol: 'SNAP',  name: 'Snap Inc.',               displaySymbol: 'SNAP.US',  color: '#fffc00', badge: 'STOCK' },
  { symbol: 'SQ',    name: 'Block Inc.',              displaySymbol: 'SQ.US',    color: '#00d64b', badge: 'STOCK' },
  { symbol: 'PLTR',  name: 'Palantir Technologies',   displaySymbol: 'PLTR.US',  color: '#000000', badge: 'STOCK' },
  { symbol: 'ZM',    name: 'Zoom Video',              displaySymbol: 'ZM.US',    color: '#2d8cff', badge: 'STOCK' },
  { symbol: 'BABA',  name: 'Alibaba Group',           displaySymbol: 'BABA.US',  color: '#ff6600', badge: 'STOCK' },
  { symbol: 'JD',    name: 'JD.com Inc.',             displaySymbol: 'JD.US',    color: '#e1251b', badge: 'STOCK' },
  { symbol: 'PDD',   name: 'Pinduoduo Inc.',          displaySymbol: 'PDD.US',   color: '#e02e24', badge: 'STOCK' },
  { symbol: 'TME',   name: 'Tencent Music',           displaySymbol: 'TME.US',   color: '#31c27c', badge: 'STOCK' },
  { symbol: 'BIDU',  name: 'Baidu Inc.',              displaySymbol: 'BIDU.US',  color: '#2319dc', badge: 'STOCK' },
  { symbol: 'NTES',  name: 'NetEase Inc.',            displaySymbol: 'NTES.US',  color: '#e40011', badge: 'STOCK' },
  { symbol: 'MSTR',  name: 'MicroStrategy',           displaySymbol: 'MSTR.US',  color: '#d9232e', badge: 'STOCK' },
  { symbol: 'COIN',  name: 'Coinbase Global',         displaySymbol: 'COIN.US',  color: '#0052ff', badge: 'STOCK' },
  { symbol: 'HOOD',  name: 'Robinhood Markets',       displaySymbol: 'HOOD.US',  color: '#00c805', badge: 'STOCK' },
  { symbol: 'AFRM',  name: 'Affirm Holdings',         displaySymbol: 'AFRM.US',  color: '#000000', badge: 'STOCK' },
  { symbol: 'UPST',  name: 'Upstart Holdings',        displaySymbol: 'UPST.US',  color: '#3adb96', badge: 'STOCK' },
];

export const CRYPTO = [
  { symbol: 'BTCUSDT',  name: 'Bitcoin',        displaySymbol: 'BTC/USDT',   color: '#f59e0b', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'ETHUSDT',  name: 'Ethereum',        displaySymbol: 'ETH/USDT',   color: '#818cf8', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'SOLUSDT',  name: 'Solana',          displaySymbol: 'SOL/USDT',   color: '#9945ff', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'BNBUSDT',  name: 'BNB',             displaySymbol: 'BNB/USDT',   color: '#f3ba2f', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'XRPUSDT',  name: 'Ripple',          displaySymbol: 'XRP/USDT',   color: '#00aae4', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'ADAUSDT',  name: 'Cardano',         displaySymbol: 'ADA/USDT',   color: '#0ea5e9', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'AVAXUSDT', name: 'Avalanche',       displaySymbol: 'AVAX/USDT',  color: '#e84142', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'DOTUSDT',  name: 'Polkadot',        displaySymbol: 'DOT/USDT',   color: '#e6007a', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'LINKUSDT', name: 'Chainlink',       displaySymbol: 'LINK/USDT',  color: '#375bd2', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'MATICUSDT',name: 'Polygon',          displaySymbol: 'MATIC/USDT', color: '#8247e5', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'DOGEUSDT', name: 'Dogecoin',        displaySymbol: 'DOGE/USDT',  color: '#c8a951', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'SHIBUSDT', name: 'Shiba Inu',       displaySymbol: 'SHIB/USDT',  color: '#ff8a00', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'LTCUSDT',  name: 'Litecoin',        displaySymbol: 'LTC/USDT',   color: '#b0b0b0', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'BCHUSDT',  name: 'Bitcoin Cash',    displaySymbol: 'BCH/USDT',   color: '#8dc351', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'UNIUSDT',  name: 'Uniswap',         displaySymbol: 'UNI/USDT',   color: '#ff007a', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'NEARUSDT', name: 'NEAR Protocol',    displaySymbol: 'NEAR/USDT',  color: '#000000', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'ATOMUSDT', name: 'Cosmos',          displaySymbol: 'ATOM/USDT',  color: '#2e3148', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'ICPUSDT',  name: 'Internet Computer',displaySymbol: 'ICP/USDT',   color: '#29abe2', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'FILUSDT',  name: 'Filecoin',        displaySymbol: 'FIL/USDT',   color: '#0090ff', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'LDOUSDT',  name: 'Lido DAO',         displaySymbol: 'LDO/USDT',   color: '#00a3ff', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'APTUSDT',  name: 'Aptos',           displaySymbol: 'APT/USDT',   color: '#000000', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'ARBUSDT',  name: 'Arbitrum',        displaySymbol: 'ARB/USDT',   color: '#28a0f0', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'OPUSDT',   name: 'Optimism',        displaySymbol: 'OP/USDT',    color: '#ff0420', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'STXUSDT',  name: 'Stacks',          displaySymbol: 'STX/USDT',   color: '#5546ff', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'GRTUSDT',  name: 'The Graph',       displaySymbol: 'GRT/USDT',   color: '#6748ff', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'AAVEUSDT', name: 'Aave',            displaySymbol: 'AAVE/USDT',  color: '#b6509e', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'MKRUSDT',  name: 'Maker',           displaySymbol: 'MKR/USDT',   color: '#1aab9b', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'RNDRUSDT', name: 'Render',          displaySymbol: 'RNDR/USDT',  color: '#000000', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'EGLDUSDT', name: 'MultiversX',      displaySymbol: 'EGLD/USDT',  color: '#000000', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'FTMUSDT',  name: 'Fantom',          displaySymbol: 'FTM/USDT',   color: '#1969ff', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'THETAUSDT',name: 'Theta Network',   displaySymbol: 'THETA/USDT', color: '#2ab8d8', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'VETUSDT',  name: 'VeChain',         displaySymbol: 'VET/USDT',   color: '#15bdff', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'HBARUSDT', name: 'Hedera',          displaySymbol: 'HBAR/USDT',  color: '#111111', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'ALGOUSDT', name: 'Algorand',        displaySymbol: 'ALGO/USDT',  color: '#000000', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'FLOWUSDT', name: 'Flow',            displaySymbol: 'FLOW/USDT',  color: '#00ef8b', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'AXSUSDT',  name: 'Axie Infinity',    displaySymbol: 'AXS/USDT',   color: '#0055ff', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'SANDUSDT', name: 'The Sandbox',     displaySymbol: 'SAND/USDT',  color: '#00aeef', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'MANAUSDT', name: 'Decentraland',    displaySymbol: 'MANA/USDT',  color: '#ff2d55', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'EOSUSDT',  name: 'EOS',             displaySymbol: 'EOS/USDT',   color: '#000000', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'KAVAUSDT', name: 'Kava',            displaySymbol: 'KAVA/USDT',  color: '#ff5c5c', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'CHZUSDT',  name: 'Chiliz',          displaySymbol: 'CHZ/USDT',   color: '#cd0124', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'GALAUSDT', name: 'Gala',            displaySymbol: 'GALA/USDT',  color: '#000000', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'IOTAUSDT', name: 'IOTA',            displaySymbol: 'IOTA/USDT',  color: '#ffffff', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'SNXUSDT',  name: 'Synthetix',       displaySymbol: 'SNX/USDT',   color: '#00d1ff', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'CRVUSDT',  name: 'Curve DAO',       displaySymbol: 'CRV/USDT',   color: '#000000', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'ENJUSDT',  name: 'Enjin Coin',      displaySymbol: 'ENJ/USDT',   color: '#624dbf', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'ZILUSDT',  name: 'Zilliqa',         displaySymbol: 'ZIL/USDT',   color: '#49c1bf', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'BATUSDT',  name: 'Basic Attention',  displaySymbol: 'BAT/USDT',   color: '#ff5000', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'XCHUSDT',  name: 'Chia',            displaySymbol: 'XCH/USDT',   color: '#48b04b', badge: 'CRYPTO', type: 'crypto' },
  { symbol: 'TUSDUSDT', name: 'TrueUSD',         displaySymbol: 'TUSD/USDT',  color: '#2b5395', badge: 'CRYPTO', type: 'crypto' },
];

export const FOREX = [
  { symbol: 'EURUSD=X',  name: 'Euro / US Dollar',           displaySymbol: 'EUR/USD',  color: '#34d399', badge: 'FOREX' },
  { symbol: 'GBPUSD=X',  name: 'British Pound / US Dollar',  displaySymbol: 'GBP/USD',  color: '#60a5fa', badge: 'FOREX' },
  { symbol: 'USDJPY=X',  name: 'US Dollar / Japanese Yen',   displaySymbol: 'USD/JPY',  color: '#f87171', badge: 'FOREX' },
  { symbol: 'AUDUSD=X',  name: 'Australian Dollar / USD',    displaySymbol: 'AUD/USD',  color: '#fb923c', badge: 'FOREX' },
  { symbol: 'USDCAD=X',  name: 'US Dollar / Canadian Dollar',displaySymbol: 'USD/CAD',  color: '#e879f9', badge: 'FOREX' },
  { symbol: 'USDCHF=X',  name: 'US Dollar / Swiss Franc',    displaySymbol: 'USD/CHF',  color: '#a78bfa', badge: 'FOREX' },
  { symbol: 'NZDUSD=X',  name: 'NZ Dollar / US Dollar',      displaySymbol: 'NZD/USD',  color: '#4ade80', badge: 'FOREX' },
  { symbol: 'EURGBP=X',  name: 'Euro / British Pound',       displaySymbol: 'EUR/GBP',  color: '#f59e0b', badge: 'FOREX' },
  { symbol: 'EURJPY=X',  name: 'Euro / Japanese Yen',        displaySymbol: 'EUR/JPY',  color: '#38bdf8', badge: 'FOREX' },
  { symbol: 'GBPJPY=X',  name: 'British Pound / Yen',        displaySymbol: 'GBP/JPY',  color: '#f43f5e', badge: 'FOREX' },
  { symbol: 'AUDJPY=X',  name: 'Australian Dollar / Yen',    displaySymbol: 'AUD/JPY',  color: '#fbbf24', badge: 'FOREX' },
  { symbol: 'CADJPY=X',  name: 'Canadian Dollar / Yen',      displaySymbol: 'CAD/JPY',  color: '#10b981', badge: 'FOREX' },
  { symbol: 'CHFJPY=X',  name: 'Swiss Franc / Japanese Yen', displaySymbol: 'CHF/JPY',  color: '#ec4899', badge: 'FOREX' },
  { symbol: 'EURAUD=X',  name: 'Euro / Australian Dollar',   displaySymbol: 'EUR/AUD',  color: '#6366f1', badge: 'FOREX' },
  { symbol: 'EURCAD=X',  name: 'Euro / Canadian Dollar',     displaySymbol: 'EUR/CAD',  color: '#f97316', badge: 'FOREX' },
  { symbol: 'EURCHF=X',  name: 'Euro / Swiss Franc',         displaySymbol: 'EUR/CHF',  color: '#8b5cf6', badge: 'FOREX' },
  { symbol: 'EURNZD=X',  name: 'Euro / NZ Dollar',           displaySymbol: 'EUR/NZD',  color: '#06b6d4', badge: 'FOREX' },
  { symbol: 'GBPAUD=X',  name: 'British Pound / AUD',        displaySymbol: 'GBP/AUD',  color: '#14b8a6', badge: 'FOREX' },
  { symbol: 'GBPCAD=X',  name: 'British Pound / CAD',        displaySymbol: 'GBP/CAD',  color: '#f59e0b', badge: 'FOREX' },
  { symbol: 'GBPCHF=X',  name: 'British Pound / CHF',        displaySymbol: 'GBP/CHF',  color: '#d946ef', badge: 'FOREX' },
  { symbol: 'GBPNZD=X',  name: 'British Pound / NZD',        displaySymbol: 'GBP/NZD',  color: '#3b82f6', badge: 'FOREX' },
  { symbol: 'AUDCAD=X',  name: 'Australian Dollar / CAD',    displaySymbol: 'AUD/CAD',  color: '#22c55e', badge: 'FOREX' },
  { symbol: 'AUDCHF=X',  name: 'Australian Dollar / CHF',    displaySymbol: 'AUD/CHF',  color: '#eab308', badge: 'FOREX' },
  { symbol: 'AUDNZD=X',  name: 'Australian Dollar / NZD',    displaySymbol: 'AUD/NZD',  color: '#f43f5e', badge: 'FOREX' },
  { symbol: 'CADCHF=X',  name: 'Canadian Dollar / CHF',      displaySymbol: 'CAD/CHF',  color: '#8b5cf6', badge: 'FOREX' },
  { symbol: 'NZDCAD=X',  name: 'NZ Dollar / Canadian Dollar',displaySymbol: 'NZD/CAD',  color: '#10b981', badge: 'FOREX' },
  { symbol: 'NZDCHF=X',  name: 'NZ Dollar / Swiss Franc',    displaySymbol: 'NZD/CHF',  color: '#ec4899', badge: 'FOREX' },
  { symbol: 'NZDJPY=X',  name: 'NZ Dollar / Japanese Yen',   displaySymbol: 'NZD/JPY',  color: '#f97316', badge: 'FOREX' },
  { symbol: 'USDMXN=X',  name: 'US Dollar / Mexican Peso',   displaySymbol: 'USD/MXN',  color: '#6366f1', badge: 'FOREX' },
  { symbol: 'USDZAR=X',  name: 'US Dollar / South African',  displaySymbol: 'USD/ZAR',  color: '#ef4444', badge: 'FOREX' },
  { symbol: 'USDTRY=X',  name: 'US Dollar / Turkish Lira',   displaySymbol: 'USD/TRY',  color: '#000000', badge: 'FOREX' },
  { symbol: 'USDINR=X',  name: 'US Dollar / Indian Rupee',   displaySymbol: 'USD/INR',  color: '#ff9933', badge: 'FOREX' },
  { symbol: 'USDSGD=X',  name: 'US Dollar / Singaporean',    displaySymbol: 'USD/SGD',  color: '#ff0000', badge: 'FOREX' },
  { symbol: 'USDHKD=X',  name: 'US Dollar / Hong Kong',      displaySymbol: 'USD/HKD',  color: '#000000', badge: 'FOREX' },
  { symbol: 'USDBRL=X',  name: 'US Dollar / Brazilian Real', displaySymbol: 'USD/BRL',  color: '#009b3a', badge: 'FOREX' },
  { symbol: 'USDPLN=X',  name: 'US Dollar / Polish Zloty',   displaySymbol: 'USD/PLN',  color: '#dc143c', badge: 'FOREX' },
  { symbol: 'USDRUB=X',  name: 'US Dollar / Russian Ruble',  displaySymbol: 'USD/RUB',  color: '#0039a6', badge: 'FOREX' },
  { symbol: 'USDSEK=X',  name: 'US Dollar / Swedish Krona',  displaySymbol: 'USD/SEK',  color: '#006aa7', badge: 'FOREX' },
  { symbol: 'USDNOK=X',  name: 'US Dollar / Norwegian Krone',displaySymbol: 'USD/NOK',  color: '#ba0c2f', badge: 'FOREX' },
  { symbol: 'USDDKK=X',  name: 'US Dollar / Danish Krone',   displaySymbol: 'USD/DKK',  color: '#c60c30', badge: 'FOREX' },
  { symbol: 'USDTWD=X',  name: 'US Dollar / Taiwan Dollar',  displaySymbol: 'USD/TWD',  color: '#ff0000', badge: 'FOREX' },
  { symbol: 'USDTHB=X',  name: 'US Dollar / Thai Baht',      displaySymbol: 'USD/THB',  color: '#00247d', badge: 'FOREX' },
  { symbol: 'USDIDR=X',  name: 'US Dollar / Indonesian',     displaySymbol: 'USD/IDR',  color: '#ff0000', badge: 'FOREX' },
  { symbol: 'USDKRW=X',  name: 'US Dollar / Korean Won',     displaySymbol: 'USD/KRW',  color: '#0047a0', badge: 'FOREX' },
  { symbol: 'USDHUF=X',  name: 'US Dollar / Hungarian Forint',displaySymbol: 'USD/HUF', color: '#436f4d', badge: 'FOREX' },
  { symbol: 'USDCZK=X',  name: 'US Dollar / Czech Koruna',   displaySymbol: 'USD/CZK',  color: '#11457e', badge: 'FOREX' },
  { symbol: 'USDILS=X',  name: 'US Dollar / Israeli Shekel', displaySymbol: 'USD/ILS',  color: '#0038b8', badge: 'FOREX' },
  { symbol: 'USDCLP=X',  name: 'US Dollar / Chilean Peso',   displaySymbol: 'USD/CLP',  color: '#0039a6', badge: 'FOREX' },
  { symbol: 'USDPHP=X',  name: 'US Dollar / Philippine Peso',displaySymbol: 'USD/PHP',  color: '#0038a8', badge: 'FOREX' },
  { symbol: 'USDCOP=X',  name: 'US Dollar / Colombian Peso', displaySymbol: 'USD/COP',  color: '#fcd116', badge: 'FOREX' },
];

export const SHARES = [
  { symbol: 'SPY',  name: 'SPDR S&P 500 ETF',           displaySymbol: 'SPY',  color: '#818cf8', badge: 'ETF' },
  { symbol: 'QQQ',  name: 'Invesco Nasdaq-100 ETF',      displaySymbol: 'QQQ',  color: '#34d399', badge: 'ETF' },
  { symbol: 'DIA',  name: 'SPDR Dow Jones ETF',          displaySymbol: 'DIA',  color: '#60a5fa', badge: 'ETF' },
  { symbol: 'IWM',  name: 'iShares Russell 2000 ETF',    displaySymbol: 'IWM',  color: '#fb923c', badge: 'ETF' },
  { symbol: 'GLD',  name: 'SPDR Gold Shares ETF',        displaySymbol: 'GLD',  color: '#fcd34d', badge: 'ETF' },
  { symbol: 'SLV',  name: 'iShares Silver Trust ETF',    displaySymbol: 'SLV',  color: '#cbd5e1', badge: 'ETF' },
  { symbol: 'TLT',  name: 'iShares 20+ Year Treasury',   displaySymbol: 'TLT',  color: '#38bdf8', badge: 'ETF' },
  { symbol: 'XLE',  name: 'Energy Select SPDR ETF',      displaySymbol: 'XLE',  color: '#4ade80', badge: 'ETF' },
  { symbol: 'XLF',  name: 'Financial Select SPDR ETF',   displaySymbol: 'XLF',  color: '#e879f9', badge: 'ETF' },
  { symbol: 'ARKK', name: 'ARK Innovation ETF',          displaySymbol: 'ARKK', color: '#f43f5e', badge: 'ETF' },
  { symbol: 'VOO',  name: 'Vanguard S&P 500 ETF',        displaySymbol: 'VOO',  color: '#a78bfa', badge: 'ETF' },
  { symbol: 'VTI',  name: 'Vanguard Total Market ETF',   displaySymbol: 'VTI',  color: '#f59e0b', badge: 'ETF' },
  { symbol: 'VEU',  name: 'Vanguard FTSE All-World',     displaySymbol: 'VEU',  color: '#3b82f6', badge: 'ETF' },
  { symbol: 'VWO',  name: 'Vanguard Emerging Markets',   displaySymbol: 'VWO',  color: '#ef4444', badge: 'ETF' },
  { symbol: 'EFA',  name: 'iShares MSCI EAFE ETF',       displaySymbol: 'EFA',  color: '#10b981', badge: 'ETF' },
  { symbol: 'AGG',  name: 'iShares Core US Aggregate',   displaySymbol: 'AGG',  color: '#6366f1', badge: 'ETF' },
  { symbol: 'BND',  name: 'Vanguard Total Bond Market',  displaySymbol: 'BND',  color: '#f97316', badge: 'ETF' },
  { symbol: 'LQD',  name: 'iShares iBoxx $ Invest Grade',displaySymbol: 'LQD',  color: '#06b6d4', badge: 'ETF' },
  { symbol: 'HYG',  name: 'iShares iBoxx $ High Yield',  displaySymbol: 'HYG',  color: '#ec4899', badge: 'ETF' },
  { symbol: 'EEM',  name: 'iShares MSCI Emerging Mkt',   displaySymbol: 'EEM',  color: '#8b5cf6', badge: 'ETF' },
  { symbol: 'IVV',  name: 'iShares Core S&P 500',        displaySymbol: 'IVV',  color: '#22c55e', badge: 'ETF' },
  { symbol: 'VUG',  name: 'Vanguard Growth ETF',         displaySymbol: 'VUG',  color: '#f43f5e', badge: 'ETF' },
  { symbol: 'VTV',  name: 'Vanguard Value ETF',          displaySymbol: 'VTV',  color: '#eab308', badge: 'ETF' },
  { symbol: 'VIG',  name: 'Vanguard Div Appreciation',   displaySymbol: 'VIG',  color: '#3b82f6', badge: 'ETF' },
  { symbol: 'VYM',  name: 'Vanguard High Div Yield',     displaySymbol: 'VYM',  color: '#10b981', badge: 'ETF' },
  { symbol: 'SCHD', name: 'Schwab US Dividend Equity',   displaySymbol: 'SCHD', color: '#6366f1', badge: 'ETF' },
  { symbol: 'JEPI', name: 'JPMorgan Equity Premium',     displaySymbol: 'JEPI', color: '#f97316', badge: 'ETF' },
  { symbol: 'JEPQ', name: 'JPMorgan Nasdaq Equity',      displaySymbol: 'JEPQ', color: '#06b6d4', badge: 'ETF' },
  { symbol: 'BITO', name: 'ProShares Bitcoin Strategy',  displaySymbol: 'BITO', color: '#f59e0b', badge: 'ETF' },
  { symbol: 'GBTC', name: 'Grayscale Bitcoin Trust',     displaySymbol: 'GBTC', color: '#818cf8', badge: 'ETF' },
  { symbol: 'IBIT', name: 'iShares Bitcoin Trust',       displaySymbol: 'IBIT', color: '#000000', badge: 'ETF' },
  { symbol: 'FBTC', name: 'Fidelity Wise Origin BTC',    displaySymbol: 'FBTC', color: '#10b981', badge: 'ETF' },
  { symbol: 'ARKB', name: 'ARK 21Shares Bitcoin ETF',    displaySymbol: 'ARKB', color: '#ff4444', badge: 'ETF' },
  { symbol: 'GDX',  name: 'VanEck Gold Miners ETF',      displaySymbol: 'GDX',  color: '#fcd34d', badge: 'ETF' },
  { symbol: 'GDXJ', name: 'VanEck Junior Gold Miners',   displaySymbol: 'GDXJ', color: '#fbbf24', badge: 'ETF' },
  { symbol: 'XOP',  name: 'SPDR Oil & Gas Exploration',  displaySymbol: 'XOP',  color: '#fb923c', badge: 'ETF' },
  { symbol: 'XLU',  name: 'Utilities Select SPDR',       displaySymbol: 'XLU',  color: '#34d399', badge: 'ETF' },
  { symbol: 'XLV',  name: 'Health Care Select SPDR',     displaySymbol: 'XLV',  color: '#60a5fa', badge: 'ETF' },
  { symbol: 'XLI',  name: 'Industrial Select SPDR',      displaySymbol: 'XLI',  color: '#f87171', badge: 'ETF' },
  { symbol: 'XLK',  name: 'Technology Select SPDR',      displaySymbol: 'XLK',  color: '#8b5cf6', badge: 'ETF' },
  { symbol: 'XLP',  name: 'Consumer Staples SPDR',       displaySymbol: 'XLP',  color: '#06b6d4', badge: 'ETF' },
  { symbol: 'XLY',  name: 'Consumer Discret SPDR',       displaySymbol: 'XLY',  color: '#ec4899', badge: 'ETF' },
  { symbol: 'XLB',  name: 'Materials Select SPDR',       displaySymbol: 'XLB',  color: '#f97316', badge: 'ETF' },
  { symbol: 'XLRE', name: 'Real Estate Select SPDR',     displaySymbol: 'XLRE', color: '#22c55e', badge: 'ETF' },
  { symbol: 'IBB',  name: 'iShares Biotechnology ETF',   displaySymbol: 'IBB',  color: '#3b82f6', badge: 'ETF' },
  { symbol: 'SOXX', name: 'iShares Semiconductor ETF',   displaySymbol: 'SOXX', color: '#10b981', badge: 'ETF' },
  { symbol: 'SMH',  name: 'VanEck Semiconductor ETF',    displaySymbol: 'SMH',  color: '#6366f1', badge: 'ETF' },
  { symbol: 'KRE',  name: 'SPDR S&P Regional Banking',   displaySymbol: 'KRE',  color: '#f97316', badge: 'ETF' },
  { symbol: 'KBE',  name: 'SPDR S&P Bank ETF',           displaySymbol: 'KBE',  color: '#06b6d4', badge: 'ETF' },
  { symbol: 'TLT',  name: 'iShares 20+ Year Treasury',   displaySymbol: 'TLT',  color: '#ec4899', badge: 'ETF' },
];

export const REAL_ESTATE = [
  { symbol: 'VNQ',  name: 'Vanguard Real Estate ETF',    displaySymbol: 'VNQ',   color: '#34d399', badge: 'REIT' },
  { symbol: 'O',    name: 'Realty Income Corp.',          displaySymbol: 'O',     color: '#818cf8', badge: 'REIT' },
  { symbol: 'AMT',  name: 'American Tower Corp.',         displaySymbol: 'AMT',   color: '#60a5fa', badge: 'REIT' },
  { symbol: 'SPG',  name: 'Simon Property Group',         displaySymbol: 'SPG',   color: '#f59e0b', badge: 'REIT' },
  { symbol: 'PLD',  name: 'Prologis Inc.',                displaySymbol: 'PLD',   color: '#4ade80', badge: 'REIT' },
  { symbol: 'EQIX', name: 'Equinix Inc.',                 displaySymbol: 'EQIX',  color: '#e879f9', badge: 'REIT' },
  { symbol: 'PSA',  name: 'Public Storage',               displaySymbol: 'PSA',   color: '#fb923c', badge: 'REIT' },
  { symbol: 'DLR',  name: 'Digital Realty Trust',         displaySymbol: 'DLR',   color: '#38bdf8', badge: 'REIT' },
  { symbol: 'WELL', name: 'Welltower Inc.',               displaySymbol: 'WELL',  color: '#a78bfa', badge: 'REIT' },
  { symbol: 'AVB',  name: 'AvalonBay Communities',        displaySymbol: 'AVB',   color: '#f43f5e', badge: 'REIT' },
  { symbol: 'EQR',  name: 'Equity Residential',           displaySymbol: 'EQR',   color: '#fcd34d', badge: 'REIT' },
  { symbol: 'ARE',  name: 'Alexandria Real Estate',        displaySymbol: 'ARE',   color: '#cbd5e1', badge: 'REIT' },
  { symbol: 'CCI',  name: 'Crown Castle Inc.',            displaySymbol: 'CCI',   color: '#6366f1', badge: 'REIT' },
  { symbol: 'SBAC', name: 'SBA Communications',          displaySymbol: 'SBAC',  color: '#f97316', badge: 'REIT' },
  { symbol: 'WY',   name: 'Weyerhaeuser Co.',             displaySymbol: 'WY',    color: '#06b6d4', badge: 'REIT' },
  { symbol: 'VICI', name: 'VICI Properties Inc.',         displaySymbol: 'VICI',  color: '#ec4899', badge: 'REIT' },
  { symbol: 'CBRE', name: 'CBRE Group Inc.',              displaySymbol: 'CBRE',  color: '#8b5cf6', badge: 'REIT' },
  { symbol: 'DRE',  name: 'Duke Realty Corp.',            displaySymbol: 'DRE',   color: '#22c55e', badge: 'REIT' },
  { symbol: 'EXR',  name: 'Extra Space Storage',          displaySymbol: 'EXR',   color: '#f43f5e', badge: 'REIT' },
  { symbol: 'CUBE', name: 'CubeSmart',                    displaySymbol: 'CUBE',  color: '#eab308', badge: 'REIT' },
  { symbol: 'MAA',  name: 'Mid-America Apartment',        displaySymbol: 'MAA',   color: '#3b82f6', badge: 'REIT' },
  { symbol: 'ESS',  name: 'Essex Property Trust',         displaySymbol: 'ESS',   color: '#10b981', badge: 'REIT' },
  { symbol: 'UDR',  name: 'UDR Inc.',                     displaySymbol: 'UDR',   color: '#6366f1', badge: 'REIT' },
  { symbol: 'INVH', name: 'Invitation Homes Inc.',        displaySymbol: 'INVH',  color: '#f97316', badge: 'REIT' },
  { symbol: 'AMH',  name: 'American Homes 4 Rent',        displaySymbol: 'AMH',   color: '#06b6d4', badge: 'REIT' },
  { symbol: 'HST',  name: 'Host Hotels & Resorts',        displaySymbol: 'HST',   color: '#ec4899', badge: 'REIT' },
  { symbol: 'VTR',  name: 'Ventas Inc.',                  displaySymbol: 'VTR',   color: '#8b5cf6', badge: 'REIT' },
  { symbol: 'PEAK', name: 'Healthpeak Properties',        displaySymbol: 'PEAK',  color: '#22c55e', badge: 'REIT' },
  { symbol: 'DOC',  name: 'Physicians Realty Trust',      displaySymbol: 'DOC',   color: '#f43f5e', badge: 'REIT' },
  { symbol: 'BXP',  name: 'Boston Properties',            displaySymbol: 'BXP',   color: '#eab308', badge: 'REIT' },
  { symbol: 'SLG',  name: 'SL Green Realty Corp.',        displaySymbol: 'SLG',   color: '#3b82f6', badge: 'REIT' },
  { symbol: 'VNO',  name: 'Vornado Realty Trust',         displaySymbol: 'VNO',   color: '#10b981', badge: 'REIT' },
  { symbol: 'WPC',  name: 'W. P. Carey Inc.',             displaySymbol: 'WPC',   color: '#6366f1', badge: 'REIT' },
  { symbol: 'STAG', name: 'STAG Industrial Inc.',         displaySymbol: 'STAG',  color: '#f97316', badge: 'REIT' },
  { symbol: 'REXR', name: 'Rexford Industrial',           displaySymbol: 'REXR',  color: '#06b6d4', badge: 'REIT' },
  { symbol: 'COLD', name: 'Americold Realty Trust',       displaySymbol: 'COLD',  color: '#ec4899', badge: 'REIT' },
  { symbol: 'FR',   name: 'First Industrial Realty',      displaySymbol: 'FR',    color: '#8b5cf6', badge: 'REIT' },
  { symbol: 'EGP',  name: 'EastGroup Properties',         displaySymbol: 'EGP',   color: '#22c55e', badge: 'REIT' },
  { symbol: 'MPW',  name: 'Medical Properties Trust',     displaySymbol: 'MPW',   color: '#f43f5e', badge: 'REIT' },
  { symbol: 'OHI',  name: 'Omega Healthcare',             displaySymbol: 'OHI',   color: '#eab308', badge: 'REIT' },
  { symbol: 'SUI',  name: 'Sun Communities Inc.',         displaySymbol: 'SUI',   color: '#3b82f6', badge: 'REIT' },
  { symbol: 'ELS',  name: 'Equity LifeStyle Prop',        displaySymbol: 'ELS',   color: '#10b981', badge: 'REIT' },
  { symbol: 'IRM',  name: 'Iron Mountain Inc.',           displaySymbol: 'IRM',   color: '#6366f1', badge: 'REIT' },
  { symbol: 'UNIT', name: 'Uniti Group Inc.',             displaySymbol: 'UNIT',  color: '#f97316', badge: 'REIT' },
  { symbol: 'VICI', name: 'VICI Properties',              displaySymbol: 'VICI',  color: '#06b6d4', badge: 'REIT' },
  { symbol: 'LAMR', name: 'Lamar Advertising',            displaySymbol: 'LAMR',  color: '#ec4899', badge: 'REIT' },
  { symbol: 'OUT',  name: 'OUTFRONT Media Inc.',          displaySymbol: 'OUT',   color: '#8b5cf6', badge: 'REIT' },
  { symbol: 'GLPI', name: 'Gaming and Leisure Prop',      displaySymbol: 'GLPI',  color: '#22c55e', badge: 'REIT' },
  { symbol: 'COR',  name: 'CoreSite Realty Corp.',        displaySymbol: 'COR',   color: '#f43f5e', badge: 'REIT' },
  { symbol: 'CONE', name: 'CyrusOne Inc.',                displaySymbol: 'CONE',  color: '#eab308', badge: 'REIT' },
];

